"""Second modification to link in user

Revision ID: 8858366348df
Revises: fd46dac1b6a6
Create Date: 2025-07-30 01:09:39.683232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8858366348df'
down_revision = 'fd46dac1b6a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=255), nullable=True))
        batch_op.drop_column('links')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('links', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('link')

    # ### end Alembic commands ###
